apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: demoproject
  namespace: default
spec:
  interval: 1m
  url: https://github.com/imnishantdevops/weather_service.git
  ref:
    branch: main
